/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TemplateImport } from './routes/template'
import { Route as CsvImport } from './routes/csv'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const MockLazyImport = createFileRoute('/mock')()
const HelperLazyImport = createFileRoute('/helper')()

// Create/Update Routes

const MockLazyRoute = MockLazyImport.update({
  id: '/mock',
  path: '/mock',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/mock.lazy').then((d) => d.Route))

const HelperLazyRoute = HelperLazyImport.update({
  id: '/helper',
  path: '/helper',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/helper.lazy').then((d) => d.Route))

const TemplateRoute = TemplateImport.update({
  id: '/template',
  path: '/template',
  getParentRoute: () => rootRoute,
} as any)

const CsvRoute = CsvImport.update({
  id: '/csv',
  path: '/csv',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/csv': {
      id: '/csv'
      path: '/csv'
      fullPath: '/csv'
      preLoaderRoute: typeof CsvImport
      parentRoute: typeof rootRoute
    }
    '/template': {
      id: '/template'
      path: '/template'
      fullPath: '/template'
      preLoaderRoute: typeof TemplateImport
      parentRoute: typeof rootRoute
    }
    '/helper': {
      id: '/helper'
      path: '/helper'
      fullPath: '/helper'
      preLoaderRoute: typeof HelperLazyImport
      parentRoute: typeof rootRoute
    }
    '/mock': {
      id: '/mock'
      path: '/mock'
      fullPath: '/mock'
      preLoaderRoute: typeof MockLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/csv': typeof CsvRoute
  '/template': typeof TemplateRoute
  '/helper': typeof HelperLazyRoute
  '/mock': typeof MockLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/csv': typeof CsvRoute
  '/template': typeof TemplateRoute
  '/helper': typeof HelperLazyRoute
  '/mock': typeof MockLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/csv': typeof CsvRoute
  '/template': typeof TemplateRoute
  '/helper': typeof HelperLazyRoute
  '/mock': typeof MockLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/csv' | '/template' | '/helper' | '/mock'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/csv' | '/template' | '/helper' | '/mock'
  id: '__root__' | '/' | '/csv' | '/template' | '/helper' | '/mock'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CsvRoute: typeof CsvRoute
  TemplateRoute: typeof TemplateRoute
  HelperLazyRoute: typeof HelperLazyRoute
  MockLazyRoute: typeof MockLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CsvRoute: CsvRoute,
  TemplateRoute: TemplateRoute,
  HelperLazyRoute: HelperLazyRoute,
  MockLazyRoute: MockLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/csv",
        "/template",
        "/helper",
        "/mock"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/csv": {
      "filePath": "csv.tsx"
    },
    "/template": {
      "filePath": "template.tsx"
    },
    "/helper": {
      "filePath": "helper.lazy.tsx"
    },
    "/mock": {
      "filePath": "mock.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
