export const commonMethods = [
  ['person.fullName', 'Full name'],
  ['person.firstName', 'First name'],
  ['person.lastName', 'Last name'],
  ['internet.exampleEmail', 'Email (example.test)'],
  ['string.uuid', 'Unique ID'],
  ['phone.number', 'Phone number'],
  ['location.city', 'City'],
  ['location.country', 'Country'],
  ['location.streetAddress', 'Street address'],
  ['company.name', 'Company'],
  ['commerce.productName', 'Product name'],
  ['commerce.price', 'Price'],
  ['number.int', 'Whole number'],
  ['number.float', 'Decimal number'],
  ['datatype.boolean', 'True / false'],
  ['date.recent', 'Recent date'],
  ['lorem.word', 'Word'],
  ['lorem.sentence', 'Sentence'],
]
